import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
